//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ControlUnit.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SectionsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SectionsEntities object using the connection string found in the 'SectionsEntities' section of the application configuration file.
        /// </summary>
        public SectionsEntities() : base("name=SectionsEntities", "SectionsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SectionsEntities object.
        /// </summary>
        public SectionsEntities(string connectionString) : base(connectionString, "SectionsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SectionsEntities object.
        /// </summary>
        public SectionsEntities(EntityConnection connection) : base(connection, "SectionsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Test> Test
        {
            get
            {
                if ((_Test == null))
                {
                    _Test = base.CreateObjectSet<Test>("Test");
                }
                return _Test;
            }
        }
        private ObjectSet<Test> _Test;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Opinion> Opinion
        {
            get
            {
                if ((_Opinion == null))
                {
                    _Opinion = base.CreateObjectSet<Opinion>("Opinion");
                }
                return _Opinion;
            }
        }
        private ObjectSet<Opinion> _Opinion;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Test EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTest(Test test)
        {
            base.AddObject("Test", test);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Opinion EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOpinion(Opinion opinion)
        {
            base.AddObject("Opinion", opinion);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SectionsModel", Name="Opinion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Opinion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Opinion object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="masterAgentIp">Initial value of the MasterAgentIp property.</param>
        /// <param name="hosts">Initial value of the Hosts property.</param>
        /// <param name="syndrom">Initial value of the Syndrom property.</param>
        public static Opinion CreateOpinion(global::System.Int32 id, global::System.String masterAgentIp, global::System.String hosts, global::System.String syndrom)
        {
            Opinion opinion = new Opinion();
            opinion.Id = id;
            opinion.MasterAgentIp = masterAgentIp;
            opinion.Hosts = hosts;
            opinion.Syndrom = syndrom;
            return opinion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MasterAgentIp
        {
            get
            {
                return _MasterAgentIp;
            }
            set
            {
                OnMasterAgentIpChanging(value);
                ReportPropertyChanging("MasterAgentIp");
                _MasterAgentIp = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MasterAgentIp");
                OnMasterAgentIpChanged();
            }
        }
        private global::System.String _MasterAgentIp;
        partial void OnMasterAgentIpChanging(global::System.String value);
        partial void OnMasterAgentIpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Hosts
        {
            get
            {
                return _Hosts;
            }
            set
            {
                OnHostsChanging(value);
                ReportPropertyChanging("Hosts");
                _Hosts = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Hosts");
                OnHostsChanged();
            }
        }
        private global::System.String _Hosts;
        partial void OnHostsChanging(global::System.String value);
        partial void OnHostsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Syndrom
        {
            get
            {
                return _Syndrom;
            }
            set
            {
                OnSyndromChanging(value);
                ReportPropertyChanging("Syndrom");
                _Syndrom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Syndrom");
                OnSyndromChanged();
            }
        }
        private global::System.String _Syndrom;
        partial void OnSyndromChanging(global::System.String value);
        partial void OnSyndromChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SectionsModel", Name="Test")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Test : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Test object.
        /// </summary>
        /// <param name="masterAgentIP">Initial value of the MasterAgentIP property.</param>
        /// <param name="iPDest">Initial value of the IPDest property.</param>
        /// <param name="iPSrc">Initial value of the IPSrc property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="testID">Initial value of the TestID property.</param>
        /// <param name="controlUnitIP">Initial value of the ControlUnitIP property.</param>
        public static Test CreateTest(global::System.String masterAgentIP, global::System.String iPDest, global::System.String iPSrc, global::System.Int32 number, global::System.Int32 id, global::System.Int32 testID, global::System.String controlUnitIP)
        {
            Test test = new Test();
            test.MasterAgentIP = masterAgentIP;
            test.IPDest = iPDest;
            test.IPSrc = iPSrc;
            test.Number = number;
            test.ID = id;
            test.TestID = testID;
            test.ControlUnitIP = controlUnitIP;
            return test;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MasterAgentIP
        {
            get
            {
                return _MasterAgentIP;
            }
            set
            {
                OnMasterAgentIPChanging(value);
                ReportPropertyChanging("MasterAgentIP");
                _MasterAgentIP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MasterAgentIP");
                OnMasterAgentIPChanged();
            }
        }
        private global::System.String _MasterAgentIP;
        partial void OnMasterAgentIPChanging(global::System.String value);
        partial void OnMasterAgentIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IPDest
        {
            get
            {
                return _IPDest;
            }
            set
            {
                OnIPDestChanging(value);
                ReportPropertyChanging("IPDest");
                _IPDest = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IPDest");
                OnIPDestChanged();
            }
        }
        private global::System.String _IPDest;
        partial void OnIPDestChanging(global::System.String value);
        partial void OnIPDestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IPSrc
        {
            get
            {
                return _IPSrc;
            }
            set
            {
                OnIPSrcChanging(value);
                ReportPropertyChanging("IPSrc");
                _IPSrc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IPSrc");
                OnIPSrcChanged();
            }
        }
        private global::System.String _IPSrc;
        partial void OnIPSrcChanging(global::System.String value);
        partial void OnIPSrcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.Int32 _Number;
        partial void OnNumberChanging(global::System.Int32 value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TestID
        {
            get
            {
                return _TestID;
            }
            set
            {
                OnTestIDChanging(value);
                ReportPropertyChanging("TestID");
                _TestID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TestID");
                OnTestIDChanged();
            }
        }
        private global::System.Int32 _TestID;
        partial void OnTestIDChanging(global::System.Int32 value);
        partial void OnTestIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ControlUnitIP
        {
            get
            {
                return _ControlUnitIP;
            }
            set
            {
                OnControlUnitIPChanging(value);
                ReportPropertyChanging("ControlUnitIP");
                _ControlUnitIP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ControlUnitIP");
                OnControlUnitIPChanged();
            }
        }
        private global::System.String _ControlUnitIP;
        partial void OnControlUnitIPChanging(global::System.String value);
        partial void OnControlUnitIPChanged();

        #endregion
    
    }

    #endregion
    
}
